package deploy

import "fmt"

// GenerateContainerdConfig returns the content for /etc/containerd/config.toml.
// For containerd 2.x the registry mirrors are configured via a hosts-dir;
// use GenerateDockerHubHostsToml / GenerateK8sRegistryHostsToml for those files.
func GenerateContainerdConfig(sandboxImage, socks5Proxy string) string {
	base := fmt.Sprintf(`# Generated by CasOS
version = 2

[plugins.'io.containerd.cri.v1.images']
  [plugins.'io.containerd.cri.v1.images'.pinned_images]
    sandbox = %q

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runc.options]
  SystemdCgroup = true
`, sandboxImage)

	if socks5Proxy == "" {
		return base
	}

	// In restricted areas: point the CRI image plugin at the hosts-dir so
	// per-registry mirrors (hosts.toml files) are picked up automatically.
	return base + `
[plugins.'io.containerd.cri.v1.images'.registry]
  config_path = '/etc/containerd/certs.d'
`
}

// GenerateDockerHubHostsToml returns the content for
// /etc/containerd/certs.d/docker.io/hosts.toml in restricted areas.
func GenerateDockerHubHostsToml() string {
	return `server = "https://registry-1.docker.io"

[host."https://docker.1ms.run"]
  capabilities = ["pull", "resolve"]
`
}

// GenerateK8sRegistryHostsToml returns the content for
// /etc/containerd/certs.d/registry.k8s.io/hosts.toml in restricted areas.
func GenerateK8sRegistryHostsToml() string {
	return `server = "https://registry.k8s.io"

[host."https://registry.aliyuncs.com/google_containers"]
  capabilities = ["pull", "resolve"]
`
}
